Fix clone project issues
Issue:
File "/usr/local/lib/python3.9/site-packages/octopus_python_client/utilities/helper.py", line 198, in log_raise_value_error 
February 28th 2023 14:12:15Error
    raise ValueError(err) 
February 28th 2023 14:12:15Error
ValueError: Error code: 400; Reason: Bad Request; {'ErrorMessage': 'There was a problem with your request.', 'Errors': ['A project with this slug already exists. Please choose a different slug.']} 

From: https://octopus-cloud-eng.tsi.lan/app#/Spaces-142/projects/dev-totem/operations/runbooks/Runbooks-441/snapshots/RunbookSnapshots-19913/runs/RunbookRuns-238810?activeTab=taskLog

The issue was caused by clone project function. During clone, client will get everything from sources project and set a new name. But it doesn't set a new slug. This cause in cloning, slug was re-used and failed in clone.

As Octopus post a blog that they are replacing name with Slug, we need to set slug also in proj cloning. 
(https://octopus.com/blog/introducing-slugs-config-as-code)

Here is setting the slug with same name string.